### ISSUE TITLE
[efiver.py] ERROR: target macOS version (10.13) not found. Aborting ...

### ISSUE THREAD

**Issue by Dids** [Piker-Alpha/HandyScripts#9]
I could swear this worked before, but I'm assuming Apple changed something so it can't find the package anymore? Possibly due to the release of 10.13.1?

```python
> ./efiver.py 

-----------------------------------------------------------
installSeed.py v4.8 Copyright (c) 2017 by Dr. Pike R. Alpha
-----------------------------------------------------------
Currently running on macOS High Sierra 10.13 Build (17A405) 
Searching for: FirmwareUpdate.pkg for macOS 10.13

ERROR: target macOS version (10.13) not found. Aborting ...
       - you may need to use the -m <version> argument

Traceback (most recent call last):
  File "./efiver.py", line 588, in <module>
    main(sys.argv[1:])
  File "./efiver.py", line 528, in main
    copyFirmwareUpdates()
  File "./efiver.py", line 503, in copyFirmwareUpdates
    shutil.copyfile(firmwareFile, targetFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/tmp/FirmwareUpdate/Scripts/Tools/EFIPayloads/MP51_0084_00B_LOCKED.fd'
```

**Comment by Dids** [comment]
Never mind. While I did update `efiver.py`, I didn't think to update `installSeed.py`.
After removing/reinstalling `installSeed.py`, everything worked fine again. :)
